dependencies:
- name: mongodb
  version: 0.4.17
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: redis
  version: 0.10.2
  repository: https://kubernetes-charts.storage.googleapis.com/
