{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "tellform.fullname" . }}
  labels:
    app: {{ template "tellform.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- if .Values.ingress.tls }}
    kubernetes.io/tls-acme: "true"
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.host }}
    secretName: {{ template "tellform.fullname" . }}-tls
{{- end }}
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "tellform.fullname" . }}
          servicePort: {{ .Values.service.tellform.internalPort }}
  - host: {{ .Values.socketHost }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "tellform.fullname" . }}
          servicePort: {{ .Values.service.socket.internalPort }}
{{- end -}}
