apiVersion: v1
kind: Service
metadata:
  name: {{ template "tellform.fullname" . }}
  labels:
    app: {{ template "tellform.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
  - name: tellform
    port: {{ .Values.service.tellform.externalPort }}
    targetPort: {{ .Values.service.tellform.internalPort }}
  - name: socket
    port: {{ .Values.service.socket.externalPort }}
    targetPort: {{ .Values.service.socket.internalPort }}
  - name: smtp
    port: 587
    targetPort: 587
  selector:
    app: {{ template "tellform.name" . }}
    release: "{{ .Release.Name }}"
