apiVersion: v1
kind: Service
metadata:
  name: {{ template "tellform.fullname" . }}
  labels:
    app: {{ template "tellform.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
  - name: http
    port: {{ .Values.service.externalPort }}
    targetPort: 3000
  selector:
    app: {{ template "tellform.name" . }}
    release: "{{ .Release.Name }}"
