apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "formio.fullname" . }}
  labels:
    app: {{ template "formio.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "formio.name" . }}
        release: "{{ .Release.Name }}"
    spec:
      containers:
      - name: {{ template "formio.fullname" . }}
        image: "{{ .Values.image }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        ports:
        - name: http
          containerPort: 3001
        - name: app
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 20
          timeoutSeconds: 5
        volumeMounts:
        - name:  config
          mountPath: /usr/src/app/config
          readOnly: true
        resources:
{{ toYaml .Values.resources | indent 10 }}
      volumes:
        - name:  config
          secret:
            secretName: {{ template "formio.fullname" . }}
 