# Secret for Signing Service
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "formio.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    heritage: {{.Release.Service | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    release: {{.Release.Name | quote }}
type: Opaque
data:
  default.json: {{ b64enc .Values.config | quote }}
