dependencies:
- name: mongodb
  version: 0.4.17
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: mariadb
  version: 1.0.5
  repository: https://kubernetes-charts.storage.googleapis.com/
